# -*- coding: utf-8 -*-
"""Addition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l6fqrybGUjixrB5mPMh5sbN2j-xzx2rw
"""

a=35
b=55
c=a+b
print(c)